// This file will be generated by Netlify build process
// For local development, you can manually add your credentials here:
// window.SUPABASE_URL = 'your-supabase-url';
// window.SUPABASE_KEY = 'your-supabase-anon-key';