import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';

const supabaseUrl = window.SUPABASE_URL;
const supabaseKey = window.SUPABASE_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error("Supabase credentials not found. Ensure netlify.js is generated by the build command.");
    const body = document.querySelector('body');
    if (body) {
        body.innerHTML = `<div style="font-family: sans-serif; padding: 2rem; text-align: center; color: red;"><h1>Configuration Error</h1><p>The application cannot connect to the backend. Please contact the site administrator.</p></div>`;
    }
}

export const supabase = createClient(supabaseUrl, supabaseKey);