import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';

const supabaseUrl = window.SUPABASE_URL || 'https://placeholder.supabase.co';
const supabaseKey = window.SUPABASE_KEY || 'placeholder-key';

if (!window.SUPABASE_URL || !window.SUPABASE_KEY || supabaseUrl === 'https://placeholder.supabase.co') {
    console.error("Supabase credentials not found. Ensure netlify.js is generated by the build command.");
    const body = document.querySelector('body');
    if (body) {
        body.innerHTML = `<div style="font-family: sans-serif; padding: 2rem; text-align: center; color: red;"><h1>Configuration Error</h1><p>The application cannot connect to the backend. Please set up your Supabase credentials in js/netlify.js file.</p><p>Replace 'your-supabase-url' and 'your-supabase-anon-key' with your actual Supabase credentials.</p></div>`;
    }
}

export const supabase = createClient(supabaseUrl, supabaseKey);